dependencies:
  - python
  - ipywidgets
  - jupyterlab
  - jupyterhub-singleuser
  - nbconvert
  - nbresuse
  - notebook
  - nteract_on_jupyter
  - numpy
  - pip
  - nbgitpuller
  - sphinx-gallery
  - pandas
  - matplotlib
