dependencies:
  - python=3.7
  - ipywidgets==7.5.1
  - jupyterlab==2.2.0
  - jupyterhub-singleuser==1.1.0
  - nbconvert==5.6.1
  - nbresuse==0.3.3
  - notebook==6.0.3
  - nteract_on_jupyter==2.1.3
pip:
  - cycler==0.10.0          
  - kiwisolver==1.2.0        
  - matplotlib==3.2.1
  - numpy==1.18.5
  - pandas==1.0.4
  - pyparsing==2.4.7          
  - python-dateutil==2.8.1    
  - pytz==2020.1              
  - scipy==1.4.1              
  - seaborn==0.10.1
  - six==1.15.0
  - pyecharts
